version: "3"

services: 
  compiler:
    build: .
    #command: 
      #- "echo 'migiuelon'"
      #- "npm run build"
    #working_dir: /app
    volumes: 
      - "./dist:/app/dist"

  itecgeo_web:
    image: nginx
    ports:
      - "8082:80"
    depends_on: 
      - compiler
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    network_mode: "general6agostoproxy_traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.itecgeo_web.rule=Host(`itecgeo-web.docker.localhost`)"